ppo with teacher actor
no imitation
MixedMlpBarlowTwinsActor(
  (mlp_encoder): Sequential(
    (0): Linear(in_features=225, out_features=512, bias=True)
    (1): ELU(alpha=1.0)
    (2): Linear(in_features=512, out_features=256, bias=True)
    (3): ELU(alpha=1.0)
    (4): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
    (5): Linear(in_features=256, out_features=128, bias=True)
    (6): ELU(alpha=1.0)
    (7): LayerNorm((128,), eps=1e-05, elementwise_affine=True)
    (8): Linear(in_features=128, out_features=23, bias=True)
  )
  (actor): MixedMlp(
    (gate): Sequential(
      (0): Linear(in_features=68, out_features=128, bias=True)
      (1): ELU(alpha=1.0)
      (2): Linear(in_features=128, out_features=128, bias=True)
      (3): ELU(alpha=1.0)
      (4): Linear(in_features=128, out_features=4, bias=True)
    )
  )
  (obs_encoder): Sequential(
    (0): Linear(in_features=45, out_features=256, bias=True)
    (1): ELU(alpha=1.0)
    (2): Linear(in_features=256, out_features=128, bias=True)
    (3): ELU(alpha=1.0)
    (4): LayerNorm((128,), eps=1e-05, elementwise_affine=True)
    (5): Linear(in_features=128, out_features=16, bias=True)
  )
  (bn): BatchNorm1d(16, eps=1e-05, momentum=0.1, affine=False, track_running_stats=True)
)
Traceback (most recent call last):
  File "./train.py", line 27, in <module>
    train(args)
  File "./train.py", line 17, in train
    ppo_runner, train_cfg = task_registry.make_alg_runner(env=env, name=args.task, args=args)
  File "/home/pi/Downloads/LocomotionWithNP3O-master/utils/task_registry.py", line 118, in make_alg_runner
    runner = runner_class(env, train_cfg_dict, log_dir, device=args.rl_device)
  File "/home/pi/Downloads/LocomotionWithNP3O-master/runner/on_constraint_policy_runner.py", line 45, in __init__
    model_dict = torch.load(os.path.join(ROOT_DIR, self.cfg['resume_path']))
  File "/home/pi/anaconda3/envs/HIT/lib/python3.8/site-packages/torch/serialization.py", line 997, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/pi/anaconda3/envs/HIT/lib/python3.8/site-packages/torch/serialization.py", line 444, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/pi/anaconda3/envs/HIT/lib/python3.8/site-packages/torch/serialization.py", line 425, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/Downloads/LocomotionWithNP3O-master/ /home/pi/Downloads/LocomotionWithNP3O-master/logs/rough_go2_constraint/Jul20_20-55-22_test_barlowtwins/model_500.pt'